// <auto-generated />
namespace OKUL_EF_CF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class m1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m1));
        
        string IMigrationMetadata.Id
        {
            get { return "202202080821537_m1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
