// <auto-generated />
namespace OKUL_EF_CF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class m21 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(m21));
        
        string IMigrationMetadata.Id
        {
            get { return "202202081104504_m21"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
